import ProjectDescription
import ProjectInfraPlugin

/// Project-specific convenience constructors for `ModuleID`.
///
/// These helpers let manifests refer to modules via enums generated by `make sync-modules`.
public extension ModuleID {
    /// Creates a Feature-layer module identifier.
    static func feature(_ module: FeatureLayer, scope: ModuleScope = .common) -> ModuleID {
        ModuleID(scope, .feature, module.rawValue)
    }

    /// Creates a Core-layer module identifier.
    static func core(_ module: CoreLayer, scope: ModuleScope = .common) -> ModuleID {
        ModuleID(scope, .core, module.rawValue)
    }

    /// Creates a Composition Root-layer module identifier.
    static func compositionRoot(_ module: CompositionRootLayer, scope: ModuleScope = .common) -> ModuleID {
        ModuleID(scope, .compositionRoot, module.rawValue)
    }

    /// Creates a Shared-layer module identifier.
    static func shared(_ module: SharedLayer, scope: ModuleScope = .common) -> ModuleID {
        ModuleID(scope, .shared, module.rawValue)
    }

    /// Creates a Utility-layer module identifier.
    static func utility(_ module: UtilityLayer, scope: ModuleScope = .common) -> ModuleID {
        ModuleID(scope, .utility, module.rawValue)
    }
}
