import ProjectDescription
import ProjectInfraPlugin

/// Project-specific convenience constructors for `ModuleID`.
///
/// These helpers let manifests refer to modules via enums generated by `make sync-modules`.
public extension ModuleID {
    /// Creates a Feature-layer module identifier.
    static func feature(_ module: FeatureLayer) -> ModuleID {
        ModuleID(.feature, module.rawValue)
    }

    /// Creates a Core-layer module identifier.
    static func core(_ module: CoreLayer) -> ModuleID {
        ModuleID(.core, module.rawValue)
    }

    /// Creates a Composition Root-layer module identifier.
    static func compositionRoot(_ module: CompositionRootLayer) -> ModuleID {
        ModuleID(.compositionRoot, module.rawValue)
    }

    /// Creates a Shared-layer module identifier.
    static func shared(_ module: SharedLayer) -> ModuleID {
        ModuleID(.shared, module.rawValue)
    }

    /// Creates a Utility-layer module identifier.
    static func utility(_ module: UtilityLayer) -> ModuleID {
        ModuleID(.utility, module.rawValue)
    }
}
