import Foundation
// AUTO-GENERATED - DO NOT EDIT.
// Generated by `python3 Scripts/sync_modules.py` from the `Modules/` directory.

/// Auto-generated list of modules in `Modules/Features/`.
///
/// Generated by `python3 Scripts/sync_modules.py` (via `make sync-modules`).
public enum FeatureLayer: String, CaseIterable, Sendable {
    case auth = "Auth"
}

/// Auto-generated list of modules in `Modules/Core/`.
///
/// Generated by `python3 Scripts/sync_modules.py` (via `make sync-modules`).
public enum CoreLayer: String, CaseIterable, Sendable {
    // No modules found in Modules/Core/
    @available(*, unavailable, message: "No modules found in this layer.")
    case __none = "__none"

    /// Returns an empty list because this layer has no modules.
    public static var allCases: [CoreLayer] { [] }
}

/// Auto-generated list of modules in `Modules/Shared/`.
///
/// Generated by `python3 Scripts/sync_modules.py` (via `make sync-modules`).
public enum SharedLayer: String, CaseIterable, Sendable {
    // No modules found in Modules/Shared/
    @available(*, unavailable, message: "No modules found in this layer.")
    case __none = "__none"

    /// Returns an empty list because this layer has no modules.
    public static var allCases: [SharedLayer] { [] }
}

/// Auto-generated list of modules in `Modules/Utility/`.
///
/// Generated by `python3 Scripts/sync_modules.py` (via `make sync-modules`).
public enum UtilityLayer: String, CaseIterable, Sendable {
    // No modules found in Modules/Utility/
    @available(*, unavailable, message: "No modules found in this layer.")
    case __none = "__none"

    /// Returns an empty list because this layer has no modules.
    public static var allCases: [UtilityLayer] { [] }
}

/// Auto-generated list of modules in `Modules/CompositionRoots/`.
///
/// Generated by `python3 Scripts/sync_modules.py` (via `make sync-modules`).
public enum CompositionRootLayer: String, CaseIterable, Sendable {
    case appCompositionRoot = "AppCompositionRoot"
    case widgetCompositionRoot = "WidgetCompositionRoot"
}
