import Foundation
// AUTO-GENERATED - DO NOT EDIT.
// Generated by `python3 Scripts/sync_modules.py` from the `Modules/` directory.

public enum FeatureLayer: String, CaseIterable, Sendable {
    case auth = "Auth"
}

public enum CoreLayer: String, CaseIterable, Sendable {
    // No modules found in Modules/Core/
    @available(*, unavailable, message: "No modules found in this layer.")
    case __none = "__none"

    public static var allCases: [CoreLayer] { [] }
}

public enum SharedLayer: String, CaseIterable, Sendable {
    // No modules found in Modules/Shared/
    @available(*, unavailable, message: "No modules found in this layer.")
    case __none = "__none"

    public static var allCases: [SharedLayer] { [] }
}

public enum UtilityLayer: String, CaseIterable, Sendable {
    // No modules found in Modules/Utility/
    @available(*, unavailable, message: "No modules found in this layer.")
    case __none = "__none"

    public static var allCases: [UtilityLayer] { [] }
}

public enum CompositionRootLayer: String, CaseIterable, Sendable {
    case appCompositionRoot = "AppCompositionRoot"
    case widgetCompositionRoot = "WidgetCompositionRoot"
}
