/// Canonical list of Apple-supported *App ID capabilities* by platform.
///
/// This catalog is derived from Apple Developer Account Help “Supported capabilities” pages and is
/// intended as the source of truth for which high-level capabilities exist in Apple’s provisioning
/// system.
///
/// Notes:
/// - Not every capability maps 1:1 to a code signing entitlement. Some require Info.plist keys
///   (for example Background Modes), and some are primarily “portal-only” configuration (for
///   example In‑App Purchase).
/// - Some entries are marked “Development only” in Apple’s tables. This catalog intentionally
///   keeps names stable and does not encode program membership / approval requirements.
public enum AppleSupportedCapabilities {
    /// Supported App ID capabilities for iOS provisioning profiles.
    public enum iOS: String, CaseIterable, Sendable {
        case fiveGNetworkSlicing = "5G Network Slicing"
        case accessWiFiInformation = "Access WiFi information"
        case appAttest = "App Attest"
        case appGroups = "App groups"
        case applePay = "Apple Pay"
        case associatedDomains = "Associated domains"
        case autoFillCredentialProvider = "AutoFill credential provider"
        case backgroundModes = "Background modes"
        case classKit = "ClassKit"
        case communicationNotifications = "Communication Notifications"
        case dataProtection = "Data protection"
        case driverKitFamilyMIDI = "DriverKit Family MIDI"
        case extendedVirtualAddressing = "Extended Virtual Addressing"
        case familyControlsDevelopment = "Family Controls (development)"
        case fileProviderTestingMode = "FileProvider Testing Mode"
        case fonts = "Fonts"
        case gameCenter = "Game Center"
        case groupActivities = "Group Activities"
        case headPose = "Head Pose"
        case healthKit = "HealthKit"
        case healthKitEstimateRecalibration = "HealthKit Estimate Recalibration"
        case hlsInterstitialPreviews = "HLS Interstitial Previews"
        case homeKit = "HomeKit"
        case hotspot = "Hotspot"
        case iCloudCloudKit = "iCloud: CloudKit"
        case iCloudDocuments = "iCloud: iCloud documents"
        case iCloudKeyValueStorage = "iCloud: iCloud key-value storage"
        case idVerifierDisplayOnly = "ID Verifier - Display Only"
        case inAppPurchase = "In-App Purchase"
        case increasedDebuggingMemoryLimit = "Increased Debugging Memory Limit"
        case interAppAudio = "Inter-App Audio"
        case journalingSuggestions = "Journaling Suggestions"
        case keychainSharing = "Keychain sharing"
        case lowLatencyHLS = "Low Latency HLS"
        case maps = "Maps"
        case matterAllowSetupPayload = "Matter Allow Setup Payload"
        case mdmManagedAssociatedDomains = "MDM Managed Associated Domains"
        case mediaDeviceDiscovery = "Media Device Discovery"
        case messagesCollaboration = "Messages Collaboration"
        case multipath = "Multipath"
        case nfcTagReading = "Near Field Communication (NFC) Tag Reading"
        case networkExtensions = "Network extensions"
        case onDemandInstallCapable = "On Demand Install Capable"
        case personalVPN = "Personal VPN"
        case pushToTalk = "Push to Talk"
        case pushNotifications = "Push notifications"
        case sensitiveContentAnalysis = "Sensitive Content Analysis"
        case sharedWithYou = "Shared with You"
        case signInWithApple = "Sign in with Apple"
        case simInsertedForWirelessCarriers = "SIM Inserted for Wireless Carriers"
        case siri = "Siri"
        case spatialAudioProfile = "Spatial Audio Profile"
        case sustainedExecution = "Sustained Execution"
        case timeSensitiveNotifications = "Time Sensitive Notifications"
        case wallet = "Wallet"
        case weatherKit = "WeatherKit"
        case wirelessAccessoryConfiguration = "Wireless Accessory Configuration"
    }

    /// Supported App ID capabilities for macOS provisioning profiles.
    public enum macOS: String, CaseIterable, Sendable {
        case appGroups = "App groups"
        case appSandbox = "App Sandbox"
        case applePay = "Apple Pay"
        case associatedDomains = "Associated domains"
        case autoFillCredentialProvider = "AutoFill credential provider"
        case classKit = "ClassKit"
        case communicationNotifications = "Communication Notifications"
        case customNetworkProtocol = "Custom Network Protocol"
        case driverKitFamilyMIDI = "DriverKit Family MIDI"
        case fileProviderTestingMode = "FileProvider Testing Mode"
        case fsKitModule = "FSKit Module"
        case gameCenter = "Game Center"
        case hardenedRuntime = "Hardened runtime"
        case headPose = "Head Pose"
        case hlsInterstitialPreviews = "HLS Interstitial Previews"
        case homeKit = "HomeKit"
        case iCloudCloudKit = "iCloud: CloudKit"
        case iCloudDocuments = "iCloud: iCloud documents"
        case iCloudKeyValueStorage = "iCloud: iCloud key-value storage"
        case inAppPurchase = "In-App Purchase"
        case keychainSharing = "Keychain sharing"
        case lowLatencyHLS = "Low Latency HLS"
        case managedAppInstallationUI = "Managed App Installation UI"
        case maps = "Maps"
        case matterAllowSetupPayload = "Matter Allow Setup Payload"
        case mdmManagedAssociatedDomains = "MDM Managed Associated Domains"
        case mediaExtensionFormatReader = "Media Extension Format Reader"
        case mediaExtensionVideoDecoder = "Media Extension Video Decoder"
        case messagesCollaboration = "Messages Collaboration"
        case networkExtensions = "Network extensions"
        case personalVPN = "Personal VPN"
        case pushNotifications = "Push notifications"
        case sensitiveContentAnalysis = "Sensitive Content Analysis"
        case sharedWithYou = "Shared with You"
        case signInWithApple = "Sign in with Apple"
        case spatialAudioProfile = "Spatial Audio Profile"
        case systemExtension = "System Extension"
        case timeSensitiveNotifications = "Time Sensitive Notifications"
        case vmNet = "VMNet"
        case weatherKit = "WeatherKit"
    }

    /// Supported App ID capabilities for tvOS provisioning profiles.
    public enum tvOS: String, CaseIterable, Sendable {
        case appAttest = "App Attest"
        case appGroups = "App groups"
        case associatedDomains = "Associated domains"
        case backgroundModes = "Background modes"
        case dataProtection = "Data protection"
        case extendedVirtualAddressing = "Extended Virtual Addressing"
        case gameCenter = "Game Center"
        case gameControllers = "Game controllers"
        case groupActivities = "Group Activities"
        case headPose = "Head Pose"
        case hlsInterstitialPreviews = "HLS Interstitial Previews"
        case homeKit = "HomeKit"
        case iCloudCloudKit = "iCloud: CloudKit"
        case iCloudKeyValueStorage = "iCloud: iCloud key-value storage"
        case inAppPurchase = "In-App Purchase"
        case keychainSharing = "Keychain sharing"
        case lowLatencyHLS = "Low Latency HLS"
        case maps = "Maps"
        case matterAllowSetupPayload = "Matter Allow Setup Payload"
        case pushNotifications = "Push notifications"
        case signInWithApple = "Sign in with Apple"
        case siri = "Siri"
        case spatialAudioProfile = "Spatial Audio Profile"
        case userManagement = "User management"
        case weatherKit = "WeatherKit"
    }

    /// Supported App ID capabilities for watchOS provisioning profiles.
    ///
    /// Note: Apple’s documentation calls out that the watchOS app target itself is limited to App
    /// Groups and Background Modes.
    public enum watchOS: String, CaseIterable, Sendable {
        case accessWiFiInformation = "Access WiFi information"
        case appGroups = "App groups"
        case applePay = "Apple Pay"
        case autoFillCredentialProvider = "AutoFill credential provider"
        case associatedDomains = "Associated domains"
        case backgroundModes = "Background modes"
        case communicationNotifications = "Communication Notifications"
        case dataProtection = "Data protection"
        case gameCenter = "Game Center"
        case healthKit = "HealthKit"
        case healthKitEstimateRecalibration = "HealthKit Estimate Recalibration"
        case hlsInterstitialPreviews = "HLS Interstitial Previews"
        case homeKit = "HomeKit"
        case hotspot = "Hotspot"
        case iCloudCloudKit = "iCloud: CloudKit"
        case iCloudDocuments = "iCloud: iCloud documents"
        case iCloudKeyValueStorage = "iCloud: iCloud key-value storage"
        case inAppPurchase = "In-App Purchase"
        case keychainSharing = "Keychain sharing"
        case lowLatencyHLS = "Low Latency HLS"
        case maps = "Maps"
        case matterAllowSetupPayload = "Matter Allow Setup Payload"
        case pushNotifications = "Push notifications"
        case shallowDepthAndPressure = "Shallow Depth and Pressure"
        case signInWithApple = "Sign in with Apple"
        case siri = "Siri"
        case timeSensitiveNotifications = "Time Sensitive Notifications"
        case wallet = "Wallet"
        case weatherKit = "WeatherKit"
    }

    /// Supported App ID capabilities for visionOS provisioning profiles.
    public enum visionOS: String, CaseIterable, Sendable {
        case appAttest = "App Attest"
        case appGroups = "App groups"
        case applePay = "Apple Pay"
        case associatedDomains = "Associated domains"
        case autoFillCredentialProvider = "AutoFill credential provider"
        case classKit = "ClassKit"
        case communicationNotifications = "Communication Notifications"
        case extendedVirtualAddressing = "Extended Virtual Addressing"
        case fileProviderTestingMode = "FileProvider Testing Mode"
        case fonts = "Fonts"
        case gameCenter = "Game Center"
        case groupActivities = "Group Activities"
        case healthKit = "HealthKit"
        case healthKitEstimateRecalibration = "HealthKit Estimate Recalibration"
        case homeKit = "HomeKit"
        case hotspot = "Hotspot"
        case iCloud = "iCloud"
        case increasedMemoryLimit = "Increased Memory Limit"
        case matterAllowSetupPayload = "Matter Allow Setup Payload"
        case mediaDeviceDiscovery = "Media Device Discovery"
        case messagesCollaboration = "Messages Collaboration"
        case multipath = "Multipath"
        case networkExtensions = "Network extensions"
        case personalVPN = "Personal VPN"
        case sharedWithYou = "Shared with You"
        case signInWithApple = "Sign in with Apple"
        case siri = "Siri"
        case spatialAudioProfile = "Spatial Audio Profile"
        case sustainedExecution = "Sustained Execution"
        case wallet = "Wallet"
        case weatherKit = "WeatherKit"
    }
}
