import Foundation
import ProjectDescription

/// Bundle identifier conventions for modules generated by the Tuist factories.
///
/// The project uses distinct bundle IDs for Interface/Impl/Testing/Tests targets so the target
/// kind can be inferred from `tuist graph -f json` and to reduce accidental cross-linking.
public enum BundleID {
    /// The kind of target within a module.
    public enum Kind: String, Sendable {
        /// Protocol/API surface of the module.
        case interface

        /// Concrete implementation of the module.
        case impl

        /// Testing helpers (mocks, fixtures) for the module.
        case testing

        /// Unit test bundle for the module.
        case tests
    }

    /// Generates a bundle identifier for a module target.
    ///
    /// Format: `<coreRoot>.mod.<scope>.<layer>.<module>.<kind>`, optionally namespaced with
    /// `TUIST_BUNDLE_ID_SUFFIX` (inserted after `com.acme`).
    public static func module(_ module: ModuleID, kind: Kind) -> String {
        let coreRoot = Environment.coreRoot.getString(default: "com.acme.akmeapp")
        let normalizedName = IdentifierSegments.normalizeSegment(module.name)
        let base = "\(coreRoot).mod.\(module.scope.rawValue).\(module.layer.rawValue).\(normalizedName).\(kind.rawValue)"
        return ConfigurationHelper.applyEnvironmentSuffix(to: base)
    }
}
